let
  Source = Csv.Document(File.Contents("C:\Users\Dylan\Downloads\COVID-19_Vaccinations_in_the_United_States_Jurisdiction (1).csv"),
                        [Delimiter=",", Columns=91, Encoding=65001, QuoteStyle=QuoteStyle.None]),
  #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
  #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"MMWR_week", Int64.Type},
                    {"Location", type text}, {"Distributed", Int64.Type}, {"Distributed_Janssen", Int64.Type}, 
                    {"Distributed_Moderna", Int64.Type}, {"Distributed_Pfizer", Int64.Type}, {"Distributed_Unk_Manuf", Int64.Type}, 
                    {"Dist_Per_100K", Int64.Type}, {"Distributed_Per_100k_5Plus", Int64.Type}, 
                    {"Distributed_Per_100k_12Plus", Int64.Type}, {"Distributed_Per_100k_18Plus", Int64.Type}, 
                    {"Distributed_Per_100k_65Plus", Int64.Type}, {"Administered", Int64.Type}, {"Administered_5Plus", Int64.Type}, 
                    {"Administered_12Plus", Int64.Type}, {"Administered_18Plus", Int64.Type}, {"Administered_65Plus", Int64.Type}, 
                    {"Administered_Janssen", Int64.Type}, {"Administered_Moderna", Int64.Type}, {"Administered_Pfizer", Int64.Type}, 
                    {"Administered_Unk_Manuf", Int64.Type}, {"Admin_Per_100K", Int64.Type}, {"Admin_Per_100k_5Plus", Int64.Type}, 
                    {"Admin_Per_100k_12Plus", Int64.Type}, {"Admin_Per_100k_18Plus", Int64.Type}, {"Admin_Per_100k_65Plus", Int64.Type}, 
                    {"Recip_Administered", Int64.Type}, {"Administered_Dose1_Recip", Int64.Type}, 
                    {"Administered_Dose1_Pop_Pct", type number}, {"Administered_Dose1_Recip_5Plus", Int64.Type}, 
                    {"Administered_Dose1_Recip_5PlusPop_Pct", type number}, {"Administered_Dose1_Recip_12Plus", Int64.Type}, {"Administered_Dose1_Recip_12PlusPop_Pct", type number}, {"Administered_Dose1_Recip_18Plus", Int64.Type}, {"Administered_Dose1_Recip_18PlusPop_Pct", type number}, {"Administered_Dose1_Recip_65Plus", Int64.Type}, {"Administered_Dose1_Recip_65PlusPop_Pct", type number}, {"Series_Complete_Yes", Int64.Type}, {"Series_Complete_Pop_Pct", type number}, {"Series_Complete_5Plus", Int64.Type}, {"Series_Complete_5PlusPop_Pct", type number}, {"Series_Complete_12Plus", Int64.Type}, {"Series_Complete_12PlusPop_Pct", type number}, {"Series_Complete_18Plus", Int64.Type}, {"Series_Complete_18PlusPop_Pct", type number}, {"Series_Complete_65Plus", Int64.Type}, {"Series_Complete_65PlusPop_Pct", type number}, {"Series_Complete_Janssen", Int64.Type}, {"Series_Complete_Moderna", Int64.Type}, {"Series_Complete_Pfizer", Int64.Type}, {"Series_Complete_Unk_Manuf", Int64.Type}, {"Series_Complete_Janssen_5Plus", Int64.Type}, {"Series_Complete_Moderna_5Plus", Int64.Type}, {"Series_Complete_Pfizer_5Plus", Int64.Type}, {"Series_Complete_Unk_Manuf_5Plus", Int64.Type}, {"Series_Complete_Janssen_12Plus", Int64.Type}, {"Series_Complete_Moderna_12Plus", Int64.Type}, {"Series_Complete_Pfizer_12Plus", Int64.Type}, {"Series_Complete_Unk_Manuf_12Plus", Int64.Type}, {"Series_Complete_Janssen_18Plus", Int64.Type}, {"Series_Complete_Moderna_18Plus", Int64.Type}, {"Series_Complete_Pfizer_18Plus", Int64.Type}, {"Series_Complete_Unk_Manuf_18Plus", Int64.Type}, {"Series_Complete_Janssen_65Plus", Int64.Type}, {"Series_Complete_Moderna_65Plus", Int64.Type}, {"Series_Complete_Pfizer_65Plus", Int64.Type}, {"Series_Complete_Unk_Manuf_65Plus", Int64.Type}, {"Additional_Doses", Int64.Type}, {"Additional_Doses_Vax_Pct", type number}, {"Additional_Doses_12Plus", Int64.Type}, {"Additional_Doses_12Plus_Vax_Pct", type number}, {"Additional_Doses_18Plus", Int64.Type}, {"Additional_Doses_18Plus_Vax_Pct", type number}, {"Additional_Doses_50Plus", Int64.Type}, {"Additional_Doses_50Plus_Vax_Pct", type number}, {"Additional_Doses_65Plus", Int64.Type}, {"Additional_Doses_65Plus_Vax_Pct", type number}, {"Additional_Doses_Moderna", Int64.Type}, {"Additional_Doses_Pfizer", Int64.Type}, {"Additional_Doses_Janssen", Int64.Type}, {"Additional_Doses_Unk_Manuf", Int64.Type}, {"Second_Booster", Int64.Type}, {"Second_Booster_50Plus", Int64.Type}, {"Second_Booster_50Plus_Vax_Pct", type number}, {"Second_Booster_65Plus", Int64.Type}, {"Second_Booster_65Plus_Vax_Pct", type number}, {"Second_Booster_Janssen", Int64.Type}, {"Second_Booster_Moderna", Int64.Type}, {"Second_Booster_Pfizer", Int64.Type}, {"Second_Booster_Unk_Manuf", Int64.Type}}),
  #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Date", "Location", "Distributed", "Dist_Per_100K", "Administered", "Administered_5Plus", "Administered_12Plus", "Administered_18Plus", "Administered_65Plus", "Admin_Per_100K", "Admin_Per_100k_5Plus", "Admin_Per_100k_12Plus", "Admin_Per_100k_18Plus", "Admin_Per_100k_65Plus", "Recip_Administered", "Administered_Dose1_Recip", "Administered_Dose1_Pop_Pct", "Administered_Dose1_Recip_5Plus", "Administered_Dose1_Recip_5PlusPop_Pct", "Administered_Dose1_Recip_12Plus", "Administered_Dose1_Recip_12PlusPop_Pct", "Administered_Dose1_Recip_18Plus", "Administered_Dose1_Recip_18PlusPop_Pct", "Administered_Dose1_Recip_65Plus", "Administered_Dose1_Recip_65PlusPop_Pct", "Series_Complete_Yes", "Series_Complete_Pop_Pct", "Series_Complete_5Plus", "Series_Complete_5PlusPop_Pct", "Series_Complete_12Plus", "Series_Complete_12PlusPop_Pct", "Series_Complete_18Plus", "Series_Complete_18PlusPop_Pct", "Series_Complete_65Plus", "Series_Complete_65PlusPop_Pct", "Additional_Doses", "Additional_Doses_Vax_Pct", "Additional_Doses_12Plus", "Additional_Doses_12Plus_Vax_Pct", "Additional_Doses_18Plus", "Additional_Doses_18Plus_Vax_Pct", "Additional_Doses_50Plus", "Additional_Doses_50Plus_Vax_Pct", "Additional_Doses_65Plus", "Additional_Doses_65Plus_Vax_Pct", "Second_Booster", "Second_Booster_50Plus", "Second_Booster_50Plus_Vax_Pct", "Second_Booster_65Plus", "Second_Booster_65Plus_Vax_Pct"}),
  #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([Date] <> #date(2022, 6, 10)) and ([Location] <> "BP2" and [Location] <> "DD2" and [Location] <> "FM" and [Location] <> "IH2" and [Location] <> "LTC" and [Location] <> "MH" and [Location] <> "PW" and [Location] <> "RP" and [Location] <> "VA2")),
  #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","MT","Montana", Replacer.ReplaceText,{"Location"}),
  #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","CA","California",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","MD","Maryland",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","VT","Vermont",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","PA","Pennsylvania",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","VA","Virginia",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","SC","South Carolina",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","AL","Alabama",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","AK","Alaska",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","AZ","Arizona",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","US","United States",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","NM","New Mexico",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","MI","Michigan",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","GU","Guam",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","OK","Oklahoma",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","AS","American Samoa",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","ID","Idaho",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","IL","Illinois",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","WY","Wyoming",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","DC","District of Columbia",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","WI","Wisconsin",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","GA","Georgia",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","RI","Rhode Island",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","PR","Puerto Rico",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","VI","U.S. Virgin Islands",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","MA","Massachusetts",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","ME","Maine",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","MN","Minnesota",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","ND","North Dakota",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","KS","Kansas",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","AR","Arkansas",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","CT","Connecticut",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","FL","Florida",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","IN","Indiana",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","NB","Nebraska",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","NV","Nevada",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35","NY","New York",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","IA","Iowa",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value38" = Table.ReplaceValue(#"Replaced Value37","DE","Delaware",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","NJ","New Jersey",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","NJ","New Jersey",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value41" = Table.ReplaceValue(#"Replaced Value40","NE","Nebraska",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value42" = Table.ReplaceValue(#"Replaced Value41","NC","North Carolina",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value43" = Table.ReplaceValue(#"Replaced Value42","TN","Tennessee",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","WA","Washington",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value45" = Table.ReplaceValue(#"Replaced Value44","NH","New Hampshire",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value46" = Table.ReplaceValue(#"Replaced Value45","MP","Northern Mariana Islands",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value47" = Table.ReplaceValue(#"Replaced Value46","UT","Utah",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value48" = Table.ReplaceValue(#"Replaced Value47","MS","Mississippi",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value49" = Table.ReplaceValue(#"Replaced Value48","OR","Oregon",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value50" = Table.ReplaceValue(#"Replaced Value49","WV","West Virginia",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value51" = Table.ReplaceValue(#"Replaced Value50","HI","Hawaii",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value52" = Table.ReplaceValue(#"Replaced Value51","LA","Louisiana",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value53" = Table.ReplaceValue(#"Replaced Value52","MO","Missouri",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value54" = Table.ReplaceValue(#"Replaced Value53","KY","Kentucky",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value55" = Table.ReplaceValue(#"Replaced Value54","CO","Colorado",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value56" = Table.ReplaceValue(#"Replaced Value55","OH","Ohio",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value57" = Table.ReplaceValue(#"Replaced Value56","SD","South Dakota",Replacer.ReplaceText,{"Location"}),
  #"Replaced Value58" = Table.ReplaceValue(#"Replaced Value57","TX","Texas",Replacer.ReplaceText,{"Location"}),
  #"Sorted Rows" = Table.Sort(#"Replaced Value58",{{"Location", Order.Ascending}, {"Date", Order.Ascending}})
in
  #"Sorted Rows"

